export const Actiontypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
    LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM",
};